src/Entity/Child.php
<?php

namespace App\Entity;

use App\Repository\ChildRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: ChildRepository::class)]
class Child
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $firstName = null;

    #[ORM\Column(length: 50)]
    private ?string $lastName = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $birthDate = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $medicalNotes = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToMany(targetEntity: Allergy::class, inversedBy: 'children')]
    private Collection $allergies;

    #[ORM\ManyToMany(targetEntity: SpecialDiet::class, inversedBy: 'children')]
    private Collection $specialDiets;

    #[ORM\ManyToOne(inversedBy: 'children')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Group $childGroup = null;

    #[ORM\OneToMany(mappedBy: 'child', targetEntity: Journal::class, cascade: ['persist', 'remove'])]
    private Collection $journals;

    #[ORM\ManyToOne(targetEntity: Icon::class)]
    #[ORM\JoinColumn(name: 'icons_id', referencedColumnName: 'id', nullable: true)]
    private ?Icon $icon = null;

    #[ORM\OneToMany(mappedBy: 'child', targetEntity: ChildPresence::class, cascade: ['persist', 'remove'])]
    private Collection $childPresences;

    #[ORM\OneToMany(mappedBy: 'child', targetEntity: PlannedPresence::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $plannedPresences;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'children')]
    private Collection $users;



    public function __construct()
    {
        $this->allergies = new ArrayCollection();
        $this->specialDiets = new ArrayCollection();
        $this->journals = new ArrayCollection();
        $this->childPresences = new ArrayCollection();
        $this->plannedPresences = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getBirthDate(): ?\DateTimeImmutable
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeImmutable $birthDate): self
    {
        $this->birthDate = $birthDate;
        return $this;
    }

    public function getMedicalNotes(): ?string
    {
        return $this->medicalNotes;
    }

    public function setMedicalNotes(?string $medicalNotes): self
    {
        $this->medicalNotes = $medicalNotes;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;
        return $this;
    }

    public function getChildGroup(): ?Group
    {
        return $this->childGroup;
    }

    public function setChildGroup(?Group $group): self
    {
        $this->childGroup = $group;
        return $this;
    }

    public function getIcon(): ?Icon
    {
        return $this->icon;
    }

    public function setIcon(?Icon $icon): self
    {
        $this->icon = $icon;
        return $this;
    }

    /** @return Collection<int, Allergy> */
    public function getAllergies(): Collection
    {
        return $this->allergies;
    }

    public function addAllergy(Allergy $allergy): self
    {
        if (!$this->allergies->contains($allergy)) {
            $this->allergies->add($allergy);
        }
        return $this;
    }

    public function removeAllergy(Allergy $allergy): self
    {
        $this->allergies->removeElement($allergy);
        return $this;
    }

    /** @return Collection<int, SpecialDiet> */
    public function getSpecialDiets(): Collection
    {
        return $this->specialDiets;
    }

    public function addSpecialDiet(SpecialDiet $diet): self
    {
        if (!$this->specialDiets->contains($diet)) {
            $this->specialDiets->add($diet);
        }
        return $this;
    }

    public function removeSpecialDiet(SpecialDiet $diet): self
    {
        $this->specialDiets->removeElement($diet);
        return $this;
    }

    /** @return Collection<int, Journal> */
    public function getJournals(): Collection
    {
        return $this->journals;
    }

    public function addJournal(Journal $journal): self
    {
        if (!$this->journals->contains($journal)) {
            $this->journals->add($journal);
            $journal->setChild($this);
        }
        return $this;
    }

    public function removeJournal(Journal $journal): self
    {
        if ($this->journals->removeElement($journal) && $journal->getChild() === $this) {
            $journal->setChild(null);
        }
        return $this;
    }

    /** @return Collection<int, ChildPresence> */
    public function getChildPresences(): Collection
    {
        return $this->childPresences;
    }

    public function addChildPresence(ChildPresence $presence): self
    {
        if (!$this->childPresences->contains($presence)) {
            $this->childPresences->add($presence);
            $presence->setChild($this);
        }
        return $this;
    }

    public function removeChildPresence(ChildPresence $presence): self
    {
        if ($this->childPresences->removeElement($presence) && $presence->getChild() === $this) {
            $presence->setChild(null);
        }
        return $this;
    }

    /** @return Collection<int, PlannedPresence> */
    public function getPlannedPresences(): Collection
    {
        return $this->plannedPresences;
    }

    public function addPlannedPresence(PlannedPresence $presence): self
    {
        if (!$this->plannedPresences->contains($presence)) {
            $this->plannedPresences->add($presence);
            $presence->setChild($this);
        }
        return $this;
    }

    public function removePlannedPresence(PlannedPresence $presence): self
    {
        if ($this->plannedPresences->removeElement($presence) && $presence->getChild() === $this) {
            $presence->setChild(null);
        }
        return $this;
    }

    public function getUsers(): Collection
    {
    return $this->users;
}
   
    public function addUser(User $user): static
    {
    if (!$this->users->contains($user)) {
        $this->users->add($user);
    }

    return $this;
    }

    public function removeUser(User $user): static
    {
    $this->users->removeElement($user);

    return $this;
    }
}

src/Entity/PlannedPresence.php
<?php

namespace App\Entity;

use App\Repository\PlannedPresenceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlannedPresenceRepository::class)]
class PlannedPresence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $week_day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $arrival_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $departure_time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:false)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
    if ($this->created_at === null) {
        $this->created_at = new \DateTimeImmutable();
    }
    }

    #[ORM\ManyToOne(inversedBy: 'plannedPresences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Child $child = null;

    #[ORM\ManyToOne(targetEntity: Semainier::class, inversedBy: 'plannedPresences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Semainier $semainier = null;


    public function getSemainier(): ?Semainier
    {
    return $this->semainier;
    }

    public function setSemainier(?Semainier $semainier): static
    {
    $this->semainier = $semainier;
    return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWeekDay(): ?string
    {
        return $this->week_day;
    }

    public function setWeekDay(string $week_day): static
    {
        $this->week_day = $week_day;

        return $this;
    }

    public function getArrivalTime(): ?\DateTimeInterface
    {
        return $this->arrival_time;
    }

    public function setArrivalTime(?\DateTimeInterface $arrival_time): static
    {
        $this->arrival_time = $arrival_time;

        return $this;
    }

    public function getDepartureTime(): ?\DateTimeInterface
    {
        return $this->departure_time;
    }

    public function setDepartureTime(?\DateTimeInterface $departure_time): static
    {
        $this->departure_time = $departure_time;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getChild(): ?Child
    {
        return $this->child;
    }

    public function setChild(?Child $child): static
    {
        $this->child = $child;

        return $this;
    }


}

src/Controller/ChildController.php
<?php

namespace App\Controller;

use App\Entity\Child;
use App\Entity\ChildPresence;
use App\Entity\Semainier;
use App\Form\ChildForm;
use App\Repository\ChildRepository;
use App\Repository\IconRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use App\Entity\PlannedPresence;
use Symfony\Component\Security\Core\Security;
use App\Repository\ChildPresenceRepository;
use App\Repository\PlannedPresenceRepository;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use App\Repository\SemainierRepository;
use App\Service\WeekHelper;
use App\Entity\Group;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

#[Route('/child')]
final class ChildController extends AbstractController
{
    #[Route(name: 'app_child_index', methods: ['GET'])]
    public function index(ChildRepository $childRepository): Response
    {
        return $this->render('child/index.html.twig', [
            'children' => $childRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_child_new', methods: ['GET', 'POST'])]
    public function new(
    Request $request, 
    EntityManagerInterface $entityManager,
    SemainierRepository $semainierRepository,
    PlannedPresenceRepository $plannedPresenceRepo, 
    // WeekHelper $weekHelper 
    ): Response {
    $child = new Child();
    $days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

    // Récupérer le semainier de la semaine en cours
    $monday = (new \DateTimeImmutable('monday this week'))->setTime(0, 0);
    $semainier = $semainierRepository->findOneBy(['week_start_date' => $monday]);
    
    if (!$semainier) {
        // Créer le semainier s'il n'existe pas
        $semainier = new Semainier();
        $semainier->setWeekStartDate($monday);
        $entityManager->persist($semainier);
    }

    foreach ($days as $day) {
        $presence = new PlannedPresence();
        $presence->setWeekDay($day);
        $presence->setChild($child);
        $presence->setSemainier($semainier); // 🔥 Lier au semainier
        $presence->setCreatedAt(new \DateTime());
        
        $child->addPlannedPresence($presence);
    }

    $form = $this->createForm(ChildForm::class, $child, [
    'is_admin' => $this->isGranted('ROLE_ADMIN'),
    ]);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Tu peux gérer createdAt ici si besoin
        foreach ($child->getPlannedPresences() as $presence) {
            $presence->setCreatedAt(new \DateTime());
        }
        $plannedPresences = $child->getPlannedPresences()->toArray();
        $plannedPresenceRepo->assignPlannedPresencesToSemainier($semainier, $plannedPresences, $entityManager);

        $entityManager->persist($child);
        $entityManager->persist($child);
        $entityManager->flush();

        return $this->redirectToRoute('app_child_index');
    }

    return $this->render('child/new.html.twig', [
        'child' => $child,
        'form' => $form->createView(),
    ]);
    }

    #[Route('/{id}/edit', name: 'app_child_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Child $child, EntityManagerInterface $entityManager, ChildRepository $childRepository, PlannedPresenceRepository $plannedPresenceRepo, SemainierRepository $semainierRepository): Response
    {
    if (!$this->isGranted('ROLE_ADMIN')) {
        return $this->render('bundles/TwigBundle/Exception/error403.html.twig', [], new Response('', 403));
    }
    $plannedPresences = $child->getPlannedPresences();
    $monday = (new \DateTimeImmutable('monday this week'))->setTime(0, 0);
    $semainier = $semainierRepository->findOneBy(['week_start_date' => $monday]);
    if (!$semainier) {
        $semainier = new Semainier();
        $semainier->setWeekStartDate($monday);
        $entityManager->persist($semainier);
    }

    if ($plannedPresences->isEmpty()) {
        $days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
        foreach ($days as $day) {
            $presence = new PlannedPresence();
            $presence->setWeekDay($day);
            $presence->setArrivalTime(null);
            $presence->setDepartureTime(null);
            $presence->setChild($child);
            $presence->setCreatedAt(new \DateTimeImmutable());
            $child->addPlannedPresence($presence);
        }
    }

    $form = $this->createForm(ChildForm::class, $child, [
    'is_admin' => $this->isGranted('ROLE_ADMIN'),
    ]);
    $form->handleRequest($request);

    $template = $this->isGranted('ROLE_PARENT') ? 'base_parent.html.twig' : 'base_admin.html.twig';

    if ($form->isSubmitted() && $form->isValid()) {
        $plannedPresences = $child->getPlannedPresences()->toArray();
        $plannedPresenceRepo->assignPlannedPresencesToSemainier($semainier, $plannedPresences, $entityManager);

        $entityManager->persist($child);
        $entityManager->flush();

        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_child_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->redirectToRoute('app_child_show', ['id' => $child->getId()], Response::HTTP_SEE_OTHER);
    }
     $children = $childRepository->findAll();
    return $this->render('child/edit.html.twig', [
        'child' => $child,
        'form' => $form->createView(),
        'base_template' => $template,  
        'children' => $children,
              
    ]);
}


    #[Route('/{id}', name: 'app_child_delete', methods: ['POST'])]
    public function delete(Request $request, Child $child, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$child->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($child);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_child_index', [], Response::HTTP_SEE_OTHER);
    }
    

    #[Route('/show/{id}', name: 'app_child_show', methods: ['GET', 'POST'])]
    public function show(Request $request, Child $child, EntityManagerInterface $entityManager, ChildRepository $childRepository, PlannedPresenceRepository $plannedPresenceRepository): Response
    {
    $user = $this->getUser();
    $children = $childRepository->findByUser($user);

    $template = $this->isGranted('ROLE_PARENT') ? 'base_parent.html.twig' : 'base_admin.html.twig';

    // Début de la semaine (lundi)
    $plannedPresences = $plannedPresenceRepository->findByChildOrderedByWeekday($child);

    return $this->render('child/show.html.twig', [
        'child' => $child,
        'children' => $children,
        'base_template' => $template,
        'planned_presences' => $plannedPresences,
        'user' => $user,
    ]);
    }


}

templates/child/_delete_form.html.twig
<form method="post" action="{{ path('app_child_delete', {'id': child.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ child.id) }}">
    <button class="buttonSimple"><p class="delete">Supprimer</p></button>
</form>

templates/child/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Edit Child{% endblock %}

{% block body %}
    <div id="titre">
    {% if child.icon is defined and child.icon %}
                <img src="{{ asset(child.icon.path) }}" alt="Icône de {{ child.firstName }}">
    {% endif %}
    <h1><span class="bold">Modifier les données de {{ child.firstName}} {{child.lastName}}</span></h1>
    </div> 
    {{include('child/_form.html.twig')}}


    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_admin_dashboard_child') }}" class="btn" id="buttonRetour">Retour</a>
    
        <form class="formButton" method="post" action="{{ path('app_child_delete', {'id': child.id}) }}" onsubmit="return confirm('Supprimer ce minus ?');" style="display: inline;">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ child.id) }}">
            <button class="btn">Supprimer</button>
        </form>
    {% endif %}
    </div>

{% endblock %}

templates/child/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'form/fields.html.twig' %}

{% block title %}Nouveau Minus{% endblock %}

{% block body %}
  
    <h1 class="titre first"><img src="{{ asset('Decor/Mask_group__2_-removebg-preview.png') }}" alt="fleur" />Créer un Minus</h1>
  

    {{ include('child/_form.html.twig') }}

{% endblock %}

templates/child/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Child{% endblock %}

{% block body %}
    <div id="titre">
    {% if child.icon is defined and child.icon %}
                <img src="{{ asset(child.icon.path) }}" alt="Icône de {{ child.firstName }}">
    {% endif %}
    <h1><span class="bold">Fiche de {{ child.firstName|capitalize }} {{ child.lastName|capitalize }}</span></h1>
    </div>
    
    <div class="information">
        <div class="titreInformation">
            <img src="{{ asset('iconsForm/babyForm.png') }}" alt="icone">
            <h2>Informations générales</h2>
        </div>
        <table class="table">
            <tbody>
                <tr><th>Prénom</th><td>{{ child.firstName|capitalize }}</td></tr>
                <tr><th>Nom</th><td>{{ child.lastName|capitalize }}</td></tr>
                <tr><th>Date de naissance</th><td>{{ child.birthDate ? child.birthDate|date('d/m/Y') : 'Non renseignée' }}</td></tr>
                <tr><th>Date de création</th><td>{{ child.createdAt ? child.createdAt|date('d/m/Y H:i') : 'Non renseignée' }}</td></tr>
            </tbody>
        </table>
    </div>

    <div class="informationMedic">
        <div class="titreInformation">
            <img src="{{ asset('iconsForm/health-and-wellness.png') }}" alt="icone">
            <h2>Informations médicales</h2>
        </div>
        <table class="table">
            <tbody>
                <tr>
                <th>Allergies</th>
                <td>{% if child.allergies|length > 0 %}
                    {% for allergy in child.allergies %}
                    {{ allergy.name|capitalize }}
                    {% endfor %}
                    {% else %}
                    <td>Aucune allergie renseignée.</td>
                    {% endif %}
                    </td>
                </tr>

                <tr>
                <th>Traitements en cours</th>
               <td>{% if child.treatments is defined and child.treatments|length > 0 %}{% for treatment in child.treatments %}{{ treatment.name|capitalize }} ({{ treatment.details|capitalize }}) {% endfor %}{% else %}Aucun traitement en cours.{% endif %}</td>

                </tr>

                <tr>
                <th>Régime alimentaire</th>
                <td>{% if child.specialDiets|length > 0 %}
                        {% for diet in child.specialDiets %}
                        {{ diet.name|capitalize }}
                        {% endfor %}
                    {% else %}
                         <td>Aucun régime spécial renseigné.</td>
                    {% endif %} 
                    </td>
                </tr>

                <tr>
            </tbody>
        </table>
    </div>
    <div class="notes">
        <div class="titreInformation">
            <img src="{{ asset('iconsForm/notes.png') }}" alt="icone">
            <h2>Notes</h2>
        </div>
         <p>{{ child.medicalNotes|capitalize ?: 'Aucune information supplémentaire.'}}</p>
    </div>

     

    <div class="planning">
        <div class="titreInformation">
            <img src="{{ asset('iconsForm/baby-book.png') }}" alt="icone">
            <h2>Planning de la semaine</h2>
        </div>
    {% if planned_presences is defined and planned_presences|length > 0 %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Jours</th>
                <th>Horaires</th>
                
            </tr>
        </thead>
        <tbody>
            {% for presence in planned_presences %}
                <tr>
                    <td>{{ presence.weekDay }}</td>
                    <td>{{ presence.arrivalTime ? presence.arrivalTime|date('H:i') : '—' }} /
                    {{ presence.departureTime ? presence.departureTime|date('H:i') : '—' }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>Aucune présence enregistrée pour cette semaine.</p>
    {% endif %}
    </div>

    <div class="responsable">
        <div class="titreInformation">
            <img src="{{ asset('iconsForm/health-and-wellness.png') }}" alt="icone">
            <h2>Responsables légaux</h2>
        </div>
       {% if child.users|length > 0 %}
        {% for user in child.users %}
            <h3>Responsable {{ loop.index }} :</h3>
            <ul>
                <li><span class="bold">Lien avec l’enfant </span>: {{ user.relationship|default('Non renseigné') }}</li>
                <li><span class="boldCap">Nom </span>: {{ user.lastName|capitalize }}</li>
                <li><span class="boldCap">Prénom </span>: {{ user.firstName|capitalize }}</li>
                <li><span class="boldCap">Téléphone</span> : {{ user.phoneNumber }}</li>
                <li><span class="boldCap">Email :</span> {{ user.email|default('non renseigné') }}</li>
            </ul>
        {% endfor %}
    {% else %}
        <p>Aucun responsable légal renseigné.</p>
    {% endif %}
    </div>
    
  
    {% if is_granted('ROLE_ADMIN')  %}
    <div class="buttonsInLine">
    <button class="buttonSimple"><a href="{{ path('app_child_edit', {'id': child.id}) }}">Modifier</a></button>
    {{ include('child/_delete_form.html.twig') }}
    <button class="buttonSimple"><a href="{{ path('app_admin_dashboard_child') }}">Retour</a></button>
    </div>
    {% endif %}
    {% if is_granted('ROLE_EDUC')  %}
    <button class="buttonSimple"><a href="{{ path('app_educateur_dashboard_child') }}">Retour</a></button>
    <a href="{{ path('app_educateur_group', { name: child.childGroup.name}) }}">Retour au groupe</a>
    {% endif %}
    {% if is_granted('ROLE_PARENT')%}
    <a href="{{ path('parent_dashboard')}}" class="btn centerButton">Retour à l'accueil Parent</a>
    {% endif %}

{% endblock %}

templates/child/show_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Child{% endblock %}

{% block body %}
    <h1>Child</h1>

    
    <h1>Fiche de {{ child.firstName|capitalize }} {{ child.lastName|capitalize }}</h1>

    <h2>Informations générales</h2>
    <table class="table">
        <tbody>
            
            <tr><th>Prénom</th><td>{{ child.firstName|capitalize }}</td></tr>
            <tr><th>Nom</th><td>{{ child.lastName|capitalize }}</td></tr>
            <tr><th>Date de naissance</th><td>{{ child.birthDate ? child.birthDate|date('d/m/Y') : 'Non renseignée' }}</td></tr>
            <tr><th>Date de création</th><td>{{ child.createdAt ? child.createdAt|date('d/m/Y H:i') : 'Non renseignée' }}</td></tr>
        </tbody>
    </table>

    <h2>Informations médicales</h2>
    <p>{{ child.medicalNotes ?: 'Aucune information médicale.' }}</p>

    <h3>Allergies</h3>
    {% if child.allergies|length > 0 %}
        <ul>
            {% for allergy in child.allergies %}
                <li>{{ allergy.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Aucune allergie renseignée.</p>
    {% endif %}

    <h3>Traitements en cours</h3>
    {# A compléter selon ta structure, ex : child.treatments #}
    {% if child.treatments is defined and child.treatments|length > 0 %}
        <ul>
            {% for treatment in child.treatments %}
                <li>{{ treatment.name }} ({{ treatment.details }})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Aucun traitement en cours.</p>
    {% endif %}

    <h3>Autres informations</h3>
    {# Exemple d’autres infos si tu en as #}
    <p>Régime alimentaire spécial :</p>
    {% if child.specialDiets|length > 0 %}
        <ul>
            {% for diet in child.specialDiets %}
                <li>{{ diet.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Aucun régime spécial renseigné.</p>
    {% endif %}

    <h2>Responsables légaux</h2>

    {% if child.users|length > 0 %}
        {% for user in child.users %}
            <h3>Responsable {{ loop.index }} :</h3>
            <ul>
                <li>Nom : {{ user.lastName|capitalize }}</li>
                <li>Prénom : {{ user.firstName|capitalize }}</li>
                <li>Téléphone : {{ user.phone }}</li>
                <li>Email : {{ user.email|default('non renseigné') }}</li>
                <li>Lien avec l’enfant : {{ user.relationship|default('Non renseigné') }}</li>
            </ul>
        {% endfor %}
    {% else %}
        <p>Aucun responsable légal renseigné.</p>
    {% endif %}

    <h2>Horaires</h2>
   {% set days = {
    'Lundi': 'Monday',
    'Mardi': 'Tuesday',
    'Mercredi': 'Wednesday',
    'Jeudi': 'Thursday',
    'Vendredi': 'Friday'
} %}

<table class="table">
    <thead>
        <tr>
            <th>Jour</th>
            <th>Arrivée</th>
            <th>Départ</th>
        </tr>
    </thead>
    <tbody>
        {% for label, day in days %}
            <tr>
                <td>{{ label }}</td>
                {% set found = false %}
                {% for presence in planned_presences %}
                    {% if presence.weekDay == day %}
                        <td>{{ presence.arrivalTime ? presence.arrivalTime|date('H:i') : '–' }}</td>
                        <td>{{ presence.departureTime ? presence.departureTime|date('H:i') : '–' }}</td>
                        {% set found = true %}
                    {% endif %}
                {% endfor %}
                {% if not found %}
                    <td>–</td>
                    <td>–</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>



    <a href="{{ path('app_admin_dashboard_child') }}">back to list</a>

    <a href="{{ path('app_child_edit', {'id': child.id}) }}">edit</a>

    {{ include('child/_delete_form.html.twig') }}
{% endblock %}