src/Entity/PlannedPresence.php
<?php

namespace App\Entity;

use App\Repository\PlannedPresenceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlannedPresenceRepository::class)]
class PlannedPresence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $week_day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $arrival_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $departure_time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:false)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
    if ($this->created_at === null) {
        $this->created_at = new \DateTimeImmutable();
    }
    }

    #[ORM\ManyToOne(inversedBy: 'plannedPresences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Child $child = null;

    #[ORM\ManyToOne(targetEntity: Semainier::class, inversedBy: 'plannedPresences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Semainier $semainier = null;


    public function getSemainier(): ?Semainier
    {
    return $this->semainier;
    }

    public function setSemainier(?Semainier $semainier): static
    {
    $this->semainier = $semainier;
    return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWeekDay(): ?string
    {
        return $this->week_day;
    }

    public function setWeekDay(string $week_day): static
    {
        $this->week_day = $week_day;

        return $this;
    }

    public function getArrivalTime(): ?\DateTimeInterface
    {
        return $this->arrival_time;
    }

    public function setArrivalTime(?\DateTimeInterface $arrival_time): static
    {
        $this->arrival_time = $arrival_time;

        return $this;
    }

    public function getDepartureTime(): ?\DateTimeInterface
    {
        return $this->departure_time;
    }

    public function setDepartureTime(?\DateTimeInterface $departure_time): static
    {
        $this->departure_time = $departure_time;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getChild(): ?Child
    {
        return $this->child;
    }

    public function setChild(?Child $child): static
    {
        $this->child = $child;

        return $this;
    }


}

src/Form/PlannedPresenceForm.php
<?php

namespace App\Form;

use App\Entity\PlannedPresence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\ChildForm;


class PlannedPresenceForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            
            ->add('week_day', TextType::class)
            ->add('arrival_time', TimeType::class, [
                'widget' => 'single_text', 
                'required' => false, 
                'empty_data' => null,
                'input' => 'datetime',])
            ->add('departure_time', TimeType::class, [
                'widget' => 'single_text', 
                'required' => false, 
                'empty_data' => null,
                'input' => 'datetime',]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PlannedPresence::class,
        ]);
    }
}

src/Controller/PlannedPresenceController.php
<?php

namespace App\Controller;

use App\Entity\PlannedPresence;
use App\Form\PlannedPresenceForm;
use App\Repository\PlannedPresenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/planned/presence')]
final class PlannedPresenceController extends AbstractController
{
    #[Route(name: 'app_planned_presence_index', methods: ['GET'])]
    public function index(PlannedPresenceRepository $plannedPresenceRepository): Response
    {
        return $this->render('planned_presence/index.html.twig', [
            'planned_presences' => $plannedPresenceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_planned_presence_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $plannedPresence = new PlannedPresence();
        $form = $this->createForm(PlannedPresenceForm::class, $plannedPresence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $planning = new PlannedPresence();
            $planning->setChild($child);
            $planning->setDay('Monday'); // par exemple
            $planning->setStartHour(new \DateTime('08:00'));
            $planning->setEndHour(new \DateTime('16:00'));
            $entityManager->persist($plannedPresence);
            $entityManager->persist($child);
            $entityManager->flush();

            return $this->redirectToRoute('app_planned_presence_index', ['id' => $child->getId()]);
        }

        return $this->render('planned_presence/new.html.twig', [
            'planned_presence' => $plannedPresence,
            'form' => $form,
            'child' => $child,
        ]);
    }
    #[Route('/{id}', name: 'app_planned_presence_show', methods: ['GET', 'POST'])]
    public function show(int $id, PlannedPresenceRepository $repo): Response
{
    $plannedPresence = $repo->find($id);
    if (!$plannedPresence) {
        throw $this->createNotFoundException('PlannedPresence not found');
    }
        return $this->render('planned_presence/show.html.twig', [
            'planned_presence' => $plannedPresence,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_planned_presence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PlannedPresence $plannedPresence, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlannedPresenceForm::class, $plannedPresence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_planned_presence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planned_presence/edit.html.twig', [
            'planned_presence' => $plannedPresence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planned_presence_delete', methods: ['POST'])]
    public function delete(Request $request, PlannedPresence $plannedPresence, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$plannedPresence->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($plannedPresence);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_planned_presence_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/planned_presence/_delete_form.html.twig
<form method="post" action="{{ path('app_planned_presence_delete', {'id': planned_presence.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planned_presence.id) }}">
    <button class="btn">Delete</button>
</form>

templates/planned_presence/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.week_day) }}
        {{ form_row(form.arrival_time) }}
        {{ form_row(form.departure_time) }}
    </div>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/planned_presence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PlannedPresence{% endblock %}

{% block body %}
    <h1>Edit PlannedPresence</h1>

    {{ include('planned_presence/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_planned_presence_index') }}">back to list</a>

    {{ include('planned_presence/_delete_form.html.twig') }}
{% endblock %}

templates/planned_presence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlannedPresence index{% endblock %}

{% block body %}
    <h1>PlannedPresence index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Week_day</th>
                <th>Arrival_time</th>
                <th>Departure_time</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for planned_presence in planned_presences %}
            <tr>
                
                <td>{{ planned_presence.weekDay ? planned_presence.weekDay|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ planned_presence.arrivalTime ? planned_presence.arrivalTime|date('H:i:s') : '' }}</td>
                <td>{{ planned_presence.createdAt ? planned_presence.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_planned_presence_show', {'id': planned_presence.id}) }}">show</a>
                    <a href="{{ path('app_planned_presence_edit', {'id': planned_presence.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_planned_presence_new') }}">Create new</a>
{% endblock %}

templates/planned_presence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PlannedPresence{% endblock %}

{% block body %}
    <h1>Create new PlannedPresence</h1>

    {{ include('planned_presence/_form.html.twig') }}

    <a href="{{ path('app_planned_presence_index') }}">back to list</a>
{% endblock %}

templates/planned_presence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlannedPresence{% endblock %}

{% block body %}
    <h1>PlannedPresence</h1>

    {% set days = {
    'Lundi': 'Monday',
    'Mardi': 'Tuesday',
    'Mercredi': 'Wednesday',
    'Jeudi': 'Thursday',
    'Vendredi': 'Friday'
} %}

<table class="table">
    <thead>
        <tr>
            <th>Jour</th>
            <th>Arrivée</th>
            <th>Départ</th>
        </tr>
    </thead>
    <tbody>
        {% for label, day in days %}
            <tr>
                <td>{{ label }}</td>
                {% set found = false %}
                {% for presence in presences %}
                    {% if presence.week_day == day %}
                        <td>{{ presence.arrival_time ? presence.arrival_time|date('H:i') : '–' }}</td>
                        <td>{{ presence.departure_time ? presence.departure_time|date('H:i') : '–' }}</td>
                        {% set found = true %}
                        
                    {% endif %}
                {% endfor %}
                {% if not found %}
                    <td>–</td>
                    <td>–</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>


    <a href="{{ path('app_planned_presence_index') }}">back to list</a>

    <a href="{{ path('app_planned_presence_edit', {'id': planned_presence.id}) }}">edit</a>

    {{ include('planned_presence/_delete_form.html.twig') }}
{% endblock %}